### PR TITLE
config-bot: add README instructions to create secret token and drop BuildConfig GitHub trigger

### PR DESCRIPTION
**Pull request by jlebon**
See individual commits.

### CODE REVIEW

**Comment by dustymabe** [comment]
> It relies on webhooks sent to the API server, which is not externally
accessible in the new cluster.

Should we open a ticket to see if they can figure out a way to accommodate us?

**Review by dustymabe — APPROVED** [review]

**Comment by jlebon** [comment]
> > It relies on webhooks sent to the API server, which is not externally
> > accessible in the new cluster.
> 
> Should we open a ticket to see if they can figure out a way to accommodate us?

Will do!

**Comment by jlebon** [comment]
https://pagure.io/fedora-infrastructure/issue/10521

**Comment by dustymabe** [comment]
Thank you!

**Pull request merged**
